### ISSUE TITLE
Herramienta para bibliografía

### ISSUE THREAD

**Issue by rubensaid** [nandorrb/tutorial_tesis#1]
@nandorrb Recomiendo usar la herramienta Mendeley para la gestión bibliográfica total (búsqueda, almacenamiento, inserción, transporte, etc). Es de la empresa Elsevier.
Usando una cuenta de la universidad se puede registrar y acceder.

**Comment by nandorrb** [comment]
Hola Rubén! Estas invitado a hacer un pull request con los cambios e información que tengas disponible.
Muchas gracias por tu apoyo!!
